### PR TITLE
Closing input stream after parsing, supporting Origins for properties

### PR DESCRIPTION
**Pull request by FingolfinTEK**
Hi! Just noticed you weren't tracking origins so I thought I'd add support for it given that you now target Spring Boot 2

### CODE REVIEW

**Comment by zeldigas** [comment]
Hi, thanks for contribution! May I ask you to do some formatting cleanup?
1. no new line at the end of class
2. formatting of method args (all on new line after method name and paren) is a bit unusual and does not match to other classes in repo. Is it possible to revert?

Also if you'd have ideas how to test this new origin tracking feature, it'd be great.

**Comment by FingolfinTEK** [comment]
Hey, sorry for the late reply, life happened :)

Hopefully the latest push addressed all the comments; since there were no new lines at the end of my files I imagined you wanted me to add them so if not, apologies - give me a shout and I'll remove them ^^

I've added a basic test for the origin, I didn't include any in the initial commit since the Spring team also didn't test the origin aspect of their Yaml and Properties loaders but it makes sense to verify it as well.

**Comment by zeldigas** [comment]
@FingolfinTEK many thanks! I'll merge and release new version soon.

**Comment by zeldigas** [comment]
Merged and released to maven central as 0.3.0

**Pull request merged**
