### PR TITLE
Springboot v2 0 0

### PR DESCRIPTION
**Pull request by meshramc**
The PR contains changes to make hocon property source work with springboot-2.0.0

### CODE REVIEW

**Comment by zeldigas** [comment]
Hey @meshramc sorry for delay, missed notification about your PR. I'll review it this weekend and publish new version in central

**Comment by zeldigas** [comment]
Merged to temp dev branch, as example is out of date now. After fix, I'll merge to master as version 0.2

**Comment by zeldigas** [comment]
Merged to master. Not sure about maven repo publish date, but will try my best to do it soon

**Comment by meshramc** [comment]
Thank you @zeldigas !

**Pull request merged**
